apiVersion: v1
kind: Service
metadata:
  namespace: avatar
  name: avatar-api
spec:
  selector:
    app: avatar-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
