apiVersion: v1
kind: Secret
metadata:
  namespace: avatar
  name: api
type: Opaque

stringData:
  # python -c "import secrets; print(secrets.token_hex(), end='')"
  pepper: TODO
  # python -c "import secrets; print(secrets.token_hex(), end='')"
  authjwt_secret_key: TODO
  # python -c "import base64; import os; print(str(base64.urlsafe_b64encode(os.urandom(32)), encoding='utf-8'), end='')"
  file_encryption_key: TODO
  # python -c "import secrets; print(secrets.token_hex(), end='')"
  avatar_first_user_password: TODO
  avatar_first_user_name: TODO