apiVersion: v1
kind: Service
metadata:
  namespace: avatar
  name: pdfgenerator
spec:
  selector:
    app: pdfgenerator
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: NodePort
