apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: avatar
  name: shared
  labels:
    type: local

spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/var/octopize/avatar/volumes/shared"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: avatar
  name: postgres
  labels:
    type: local

spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/octopize/avatar/volumes/postgres"
