apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: avatar

spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:14.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /var/run/secrets
              name: secrets
              readOnly: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /var/run/secrets/db_password
            - name: POSTGRES_USER_FILE
              value: /var/run/secrets/db_user
            - name: POSTGRES_DB_FILE
              value: /var/run/secrets/db_name


      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: secrets
          secret:
            secretName: postgres-secret