apiVersion: v1
kind: Secret
metadata:
  name: api
  labels:
    {{- include "avatar.labels" . | nindent 4 }}
type: Opaque

data:
  pepper: {{ .Values.api.pepper | b64enc | quote }}
  authjwt_secret_key: {{ .Values.api.authjwtSecretKey | b64enc | quote }}
  file_encryption_key: {{ .Values.api.fileEncryptionKey | b64enc | quote }}
  first_user_name: {{ .Values.api.firstUserName | b64enc | quote }}
  first_user_password: {{ .Values.api.firstUserPassword | b64enc | quote }}
  db_username: {{ .Values.dbUsername | b64enc | quote }}
  db_password: {{ .Values.dbPassword | b64enc | quote }}
