apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatar-api
  labels:
    {{- include "avatar.labels" . | nindent 4 }}
    app.kubernetes.io/component: api

spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: api
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "avatar.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ .Values.gcp.ksaName | default "" | quote }}
      containers:
        - name: avatar-api
          image: quay.io/octopize/api:{{ .Values.avatarVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/run/secrets
              name: secrets
              readOnly: true
          {{ if .Values.debug.storage.useLocal }}
            - mountPath: {{ .Values.api.sharedStoragePath }}
              name: avatar-pv-storage
          {{ end }}
          resources:
            requests:
              memory: {{ .Values.resources.apiMemoryRequest }}
              cpu: {{ .Values.resources.apiCpuRequest }}
            limits:
              memory: {{ .Values.resources.apiMemoryRequest }}
              cpu: {{ .Values.resources.apiCpuRequest }}
          env:
            {{- template "avatar.app_env" }}
            - name: RATELIMIT_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: RATELIMIT_REDIS_URL
            - name: USE_EMAIL_AUTHENTICATION
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: USE_EMAIL_AUTHENTICATION
            {{ if .Values.debug.storage.useLocal }}
            - name: USER_ID
              value: "1000"
            {{ end }}
          ports:
            - name: api
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8000
              httpHeaders:
              - name: Host
                value: "127.0.0.1"
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
            httpGet:
              path: "/health"
              port: 8000
              httpHeaders:
              - name: Host
                value: "127.0.0.1"
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 2
        {{- template "avatar.db_proxy" . }}
      imagePullSecrets:
        - name: docker-local-pull-secret
      volumes:
        - name: secrets
          secret:
            secretName: api
    {{ if .Values.debug.storage.useLocal }}
        - name: avatar-pv-storage
          persistentVolumeClaim:
            claimName: avatar-pv-claim
      securityContext:
        runAsUser: 0
    {{ end }}