apiVersion: v1
kind: Service
metadata:
  name: avatar-api
  labels:
    {{- include "avatar.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

spec:
  type: NodePort
  selector:
    # Match theses labels
    app.kubernetes.io/component: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
