apiVersion: v1
kind: Service
metadata:
  name: avatar-api
  labels:
    {{- include "avatar.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8000":"api-backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'

spec:
  # type: NodePort
  # ClusterIP for NEG on GCP
  type: ClusterIP
  selector:
    # Match theses labels
    app.kubernetes.io/component: api
  ports:
    - name: api
      protocol: TCP
      port: 8000
      targetPort: api
