{{- if .Values.gcp.useGCP }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gcp.ksaName | quote }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.gsaEmail | quote }}
  labels:
    {{- include "avatar.labels" . | nindent 4 }}
{{- end }}
