apiVersion: v1
kind: PersistentVolume
metadata:
  name: avatar-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/avatar/shared_files"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avatar-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi