apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: avatar
  name: avatar-api
  labels:
    app: avatar-api
spec:
  selector:
    matchLabels:
      app: avatar-api
  replicas: 1
  template:
    metadata:
      labels:
        app: avatar-api
    spec:
      containers:
        - name: avatar-api
          image: quay.io/octopize/api:latest
          volumeMounts:
            - mountPath: /shared
              name: shared
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env:
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: ENV_NAME
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: CELERY_RESULT_BACKEND
            - name: RATELIMIT_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: RATELIMIT_REDIS_URL
            - name: BASE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: BASE_API_URL
            - name: PDFGENERATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: PDFGENERATOR_URL
            - name: IS_SENTRY_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: IS_SENTRY_ENABLED
            - name: IS_TELEMETRY_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: IS_TELEMETRY_ENABLED
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PEPPER
              valueFrom:
                secretKeyRef:
                  name: api
                  key: pepper
            - name: AUTHJWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api
                  key: authjwt_secret_key
            - name: FILE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: api
                  key: file_encryption_key
            - name: AVATAR_FIRST_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api
                  key: avatar_first_user_password
            - name: AVATAR_FIRST_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: AVATAR_FIRST_USER_NAME
            - name: TASK_MAX_TIME_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: TASK_MAX_TIME_LIMIT
          ports:
            - containerPort: 8000
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8000/health
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 2
      imagePullSecrets:
        - name: docker-local-pull-secret
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared
