apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: avatar
  name: avatar-cron
  labels:
    app: avatar-cron
spec:
  selector:
    matchLabels:
      app: avatar-cron
  replicas: 1
  template:
    metadata:
      labels:
        app: avatar-cron
    spec:
      containers:
        - name: avatar-cron
          image: quay.io/octopize/api:latest
          command: ["celery", "-A", "api.lib.task", "beat", "--loglevel=info"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "200m"
          env:
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: ENV_NAME
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: CELERY_RESULT_BACKEND
            - name: BASE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: avatar-config
                  key: BASE_API_URL
            - name: DB_PORT
              value: "0" # DB_PORT is set by k8s to "tcp://" which fails validation
      imagePullSecrets:
        - name: docker-local-pull-secret
