apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: avatar
type: Opaque

data:
  # encode with `echo -n "avatar" | base64`
  dbname: YXZhdGFy # default "avatar"
  username: YXZhdGFy # default "avatar"

  # python -c "import secrets; print(secrets.token_hex(), end='')" | base64
  password: TODO
