apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: avatar
  name: redis
  labels:
    app: redis

spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: master
          image: redis:6.2.6-alpine
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
