{{- if .Values.authentik.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: authentik-avatar-blueprint
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "avatar.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- /*
    Load the blueprint YAML file from the static/blueprint/ directory.
    The blueprint contains !Env tags that authentik resolves at apply time
    from environment variables injected into the authentik pods.
  */ -}}
  octopize-avatar-blueprint.yaml: |
    {{- .Files.Get "static/blueprint/octopize-avatar-blueprint.yaml" | nindent 4 }}
{{- end }}
