apiVersion: v1
kind: ConfigMap
metadata:
  name: avatar-config
  labels:
    {{- include "avatar.labels" . | nindent 4 }}

data:
  IS_TELEMETRY_ENABLED: {{ .Values.api.isTelemetryEnabled | quote }}
  IS_SENTRY_ENABLED: {{ .Values.api.isSentryEnabled | quote }}
  DB_HOST: {{- if .Values.gcp.dbInstanceConnectionName }} "127.0.0.1" {{- else }} {{ .Values.dbHost | quote }} {{- end }}
  DB_PORT: {{ .Values.dbPort | quote }}
  ENV_NAME: {{ .Values.envName | quote }}
  # Set to externally accessible API url (should be with https)
  AVATAR_API_URL: {{ .Values.api.baseUrl | quote }}
  AVATAR_PDFGENERATOR_URL: http://{{ .Values.pdfgeneratorHost }}:{{ .Values.pdfgeneratorPort }}
  SHARED_STORAGE_PATH: {{ .Values.api.sharedStoragePath | quote }}
  AWS_ENDPOINT_URL: {{ .Values.api.awsEndpointUrl | quote }}
  USE_EMAIL_AUTHENTICATION: {{ .Values.api.useEmailAuthentication | default "false" | quote }}
  MAX_ALLOWED_DIMENSIONS_PER_DATASET: {{ .Values.api.maxAllowedDimensionsPerDataset | quote }}
  MAX_ALLOWED_LINES_PER_DATASET: {{ .Values.api.maxAllowedLinesPerDataset | quote }}
  LOG_LEVEL: {{ .Values.api.logLevel | quote }}
  DELETE_FILES_USING_CRONJOB: {{ .Values.api.deleteFilesUsingCronjob | quote }}