apiVersion: v1
kind: Service
metadata:
  name: avatar-pdf
  labels:
    {{- include "avatar.labels" . | nindent 4 }}

spec:
  selector:
    app.kubernetes.io/component: pdfgenerator
  ports:
    - protocol: TCP
      port: {{ .Values.pdfgeneratorPort}}
      targetPort: pdfgenerator
  type: ClusterIP
