name: Release Deploy Tool

on:
  workflow_dispatch:
  push:
    tags:
      - "deploy-tool-v*.*.*"

jobs:
  deploy-tool-pypi-release:
    name: Release deploy-tool on PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ${{ github.workspace }}/deployment-tool

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          working-directory: ${{ github.workspace }}/deployment-tool
          enable-cache: true

      - name: Install Just
        uses: extractions/setup-just@v3


      - name: Install dependencies
        run: just install

      - name: Build and publish project on PyPI
        run: just release
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_DEPLOY_TOOL_TOKEN }}

  deploy-tool-docker-release:
    name: Release deploy-tool Docker image on Quay
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            quay.io/octopize/deploy-tool
          labels: |
            org.opencontainers.image.description=Octopize Avatar deployment configuration tool
          tags: |
            type=match,pattern=deploy-tool-v(\d+\.\d+\.\d+),group=1
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: deployment-tool
          push: true
          pull: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            GIT_REF=${{ github.ref_name }}
